const $ = selector => document.querySelector(selector);
const months = ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];
const state = {catalog:null,year:'2006',month:1,show:null,data:null,playingShow:null,playingData:null,tab:'segments',activeSegment:null,search:'',mediaShowId:null};
const indexes={},showCache={}; let lastHistoryWrite=0;
const time = seconds => {seconds=Math.max(0,Math.floor(seconds||0));return `${Math.floor(seconds/3600)}:${String(Math.floor(seconds%3600/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`};
const duration = seconds => `${Math.floor(seconds/3600)} hr ${Math.floor(seconds%3600/60)} min`;
const shortDate = date => {const [year,month,day]=date.split('-');return `${month}/${day}/${year.slice(2)}`};
const title = show => show.topics?.[0]?.title || 'Archive broadcast';
const allShows=()=>Object.values(state.catalog||{}).flat(); const yearShows=()=>state.catalog?.[state.year]||[];
const route=()=>location.hash.replace(/^#/,'').split('/'); const go=value=>{location.hash=value}; const showRoute=(id,seconds=0)=>go(`show/${id}/${Math.floor(seconds)}`);
const esc=value=>String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
async function loadShowData(id,show){if(showCache[id])return showCache[id];showCache[id]=show?.transcriptAvailable?await fetch(`data/shows/${id}.json`).then(response=>response.json()):{topics:show?.topics||[],transcript:[]};return showCache[id];}
function highlight(text,words){let value=esc(text);for(const word of words)value=value.replace(new RegExp(`(${word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'gi'),'<mark>$1</mark>');return value;}
const savedHistory=()=>{try{return JSON.parse(localStorage.getItem('aircheck-history')||'[]')}catch{return[]}};
function remember(){
  const audio=$('#audio'), show=state.playingShow; if(!show)return;
  const entry={id:show.id,date:show.date,title:title(show),position:audio.currentTime||0,duration:audio.duration||show.duration||0,updatedAt:Date.now()};
  const next=[entry,...savedHistory().filter(item=>item.id!==show.id)].slice(0,30); localStorage.setItem('aircheck-history',JSON.stringify(next));
}
function updateMediaSession(){
  if(!('mediaSession'in navigator)||!state.playingShow)return;
  if(typeof MediaMetadata!=='undefined'&&state.mediaShowId!==state.playingShow.id){navigator.mediaSession.metadata=new MediaMetadata({title:title(state.playingShow),artist:state.playingShow.date,album:'Aircheck',artwork:[{src:'assets/howard1.png',sizes:'512x512',type:'image/png'}]});state.mediaShowId=state.playingShow.id;}
  navigator.mediaSession.playbackState=$('#audio').paused?'paused':'playing';
}
function card(show){const d=new Date(`${show.date}T00:00:00Z`);return `<button class="show" data-show="${show.id}"><div class="date">${String(d.getUTCDate()).padStart(2,'0')}<small>${d.toLocaleDateString('en',{weekday:'short'}).toUpperCase()}</small></div><div><strong>${esc(title(show))}</strong><p>${duration(show.duration)}</p></div><span class="arrow">›</span></button>`;}
function historyShelf(){const byId=new Map(allShows().map(show=>[show.id,show]));const rows=savedHistory().map(item=>({...item,show:byId.get(item.id)})).filter(item=>item.show).slice(0,4);return rows.length?`<section class="history"><p class="kicker">LISTENING HISTORY</p><h2>Pick up the signal</h2>${rows.map(item=>`<button class="history-row" data-history="${item.id}" data-history-time="${item.position}"><span>${shortDate(item.date)}</span><strong>${esc(item.title)}</strong><em>${time(item.position)} · ${new Date(item.updatedAt).toLocaleDateString('en',{month:'short',day:'numeric'})}</em></button>`).join('')}</section>`:'';}
function library(){
  const list=yearShows().filter(show=>new Date(`${show.date}T00:00:00Z`).getUTCMonth()+1===state.month);
  $('#app').innerHTML=`<div class="shell"><aside class="rail"><p class="kicker">${state.year==='2006'?'THE FIRST SATELLITE YEAR':'SATELLITE YEAR TWO'}</p><img src="assets/howard1.png" alt="Howard Stern at the microphone">${historyShelf()}</aside><section class="library"><header class="library-head"><div class="date-wheel" aria-label="Browse broadcast date"><label><select id="month-wheel">${months.map((month,index)=>`<option value="${index+1}" ${state.month===index+1?'selected':''}>${month[0]+month.slice(1).toLowerCase()}</option>`).join('')}</select></label><label><select id="year-wheel"><option value="2006" ${state.year==='2006'?'selected':''}>2006</option><option value="2007" ${state.year==='2007'?'selected':''}>2007</option></select></label></div></header><div class="show-grid">${list.map(card).join('')}</div></section></div>`;
}
async function detail(id){
  const show=allShows().find(item=>item.id===id);if(!show)return go('home');
  state.show=show;state.data=await loadShowData(id,show);state.activeSegment=null;renderDetail();syncTranscript();
}
function renderDetail(){const show=state.show,data=state.data,playing=state.playingShow?.id===show.id&&!$('#audio').paused;$('#app').innerHTML=`<article class="detail"><button class="text-back" id="show-back">← Back to broadcasts</button><header class="show-hero"><div><p class="hero-date">${shortDate(show.date)}</p><h1>${esc(title(show))}</h1><p>${duration(show.duration)}</p><button class="hero-play" data-play="0">${playing?'Stop the Clock':'HeyNow'}</button></div><img src="assets/howard2.png" alt="Howard Stern in studio"></header><div class="tabs"><button data-tab="segments" class="${state.tab==='segments'?'active':''}">Segments</button><button data-tab="transcript" class="${state.tab==='transcript'?'active':''}">Transcript</button></div><section class="tab-content">${state.tab==='segments'?segments(data.topics):transcript(data.transcript)}</section></article>`;}
function segments(items){return `<div class="topics">${items.map(topic=>`<button class="topic" data-play="${topic.startTime}"><time>${time(topic.startTime)}</time><h2>${esc(topic.title)}</h2><p>${esc(topic.summary)}</p></button>`).join('')}</div>`;}
function transcript(items){return items.length?`<div class="transcript"><p class="transcript-note">Swipe sideways for Segments · the line currently on air is highlighted.</p>${items.map((segment,index)=>`<button class="segment" data-segment="${index}" data-play="${segment.startTime}"><time>${time(segment.startTime)}</time><span>${esc(segment.text)}</span></button>`).join('')}</div>`:'<p class="empty">Transcript is not available for this broadcast.</p>';}
function activeCopy(){const audio=$('#audio'),data=state.playingData;const active=data?.transcript?.find((segment,index)=>audio.currentTime>=segment.startTime&&audio.currentTime<(data.transcript[index+1]?.startTime??Infinity));const topic=data?.topics?.find((item,index)=>audio.currentTime>=item.startTime&&audio.currentTime<(data.topics[index+1]?.startTime??Infinity));return active?.text||topic?.title||`Listening from ${time(audio.currentTime)}`;}
function updatePlayer(){
  const audio=$('#audio'),show=state.playingShow;if(!show)return;$('#bottom-player').hidden=false;
  const max=Math.max(1,audio.duration||show.duration||1),value=audio.currentTime||0,position=`${Math.min(100,Math.max(0,value/max*100))}%`,copy=activeCopy();
  $('#player-title strong').textContent=title(show);$('#player-date').textContent=`${shortDate(show.date)} · ON AIR`;$('#player-segment').textContent=copy;
  $('#progress').max=max;$('#progress').value=value;$('#progress').style.setProperty('--playhead-position',position);$('#mic-playhead').style.setProperty('--playhead-position',position);$('#elapsed').textContent=time(value);$('#remaining').textContent=`−${time(max-value)}`;
  $('#player-toggle').textContent=audio.paused?'▶':'Ⅱ';$('#player-toggle').setAttribute('aria-label',audio.paused?'Play current broadcast':'Pause current broadcast');const top=$('#toggle-button');top.textContent=audio.paused?'▶ Play':'Ⅱ Pause';
  const hero=$('.hero-play');if(hero&&state.show?.id===show.id)hero.textContent=audio.paused?'HeyNow':'Stop the Clock';
  $('#mute-volume').classList.toggle('muted',audio.muted||audio.volume===0);$('#volume-state').textContent=(audio.muted||audio.volume===0)?'MUTE':'';
  if(!$('#expanded-player').hidden){const activeTopic=state.playingData?.topics?.find((topic,index)=>value>=topic.startTime&&value<(state.playingData.topics[index+1]?.startTime??Infinity));$('#expanded-date').textContent=shortDate(show.date);$('#expanded-title').textContent=activeTopic?.title||title(show);$('#expanded-segment').textContent=copy;$('#expanded-progress').max=max;$('#expanded-progress').value=value;$('#expanded-elapsed').textContent=time(value);$('#expanded-remaining').textContent=`−${time(max-value)}`;$('#expanded-toggle').textContent=audio.paused?'▶':'Ⅱ';}
  updateMediaSession();
}
function play(show,at=0,data=null){const audio=$('#audio');state.playingShow=show;state.playingData=data||((state.show?.id===show.id)?state.data:null);if(audio.src!==new URL(show.url,location.href).href)audio.src=show.url;audio.currentTime=at;audio.play();updatePlayer();syncTranscript();}
function togglePlayback(){const audio=$('#audio');if(!state.playingShow)return state.show&&play(state.show,0,state.data);audio.paused?audio.play():audio.pause();updatePlayer();}
function seek(value){$('#audio').currentTime=Number(value);updatePlayer();syncTranscript();}
function syncTranscript(){if(!state.data?.transcript?.length||state.show?.id!==state.playingShow?.id)return;const now=$('#audio').currentTime||0,topicIndex=state.data.topics?.findIndex((topic,i)=>now>=topic.startTime&&now<(state.data.topics[i+1]?.startTime??Infinity));document.querySelector('.topic.active')?.classList.remove('active');if(topicIndex>=0)document.querySelectorAll('.topic')[topicIndex]?.classList.add('active');const index=state.data.transcript.findIndex((segment,i)=>now>=segment.startTime&&now<(state.data.transcript[i+1]?.startTime??Infinity));if(index<0||index===state.activeSegment)return;document.querySelector('.segment.active')?.classList.remove('active');const row=document.querySelector(`[data-segment="${index}"]`);row?.classList.add('active');if(state.tab==='transcript'&&row&&state.activeSegment!==null)row.scrollIntoView({block:'center',behavior:'smooth'});state.activeSegment=index;}
function openExpanded(){if(!state.playingShow)return;$('#expanded-player').hidden=false;document.body.classList.add('player-expanded');updatePlayer();}
function closeExpanded(){$('#expanded-player').hidden=true;document.body.classList.remove('player-expanded');}
async function random(){const candidates=allShows().filter(show=>show.transcriptAvailable),show=candidates[Math.floor(Math.random()*candidates.length)],data=await loadShowData(show.id,show),pieces=data.topics.length?data.topics:data.transcript,pick=pieces[Math.floor(Math.random()*pieces.length)];play(show,pick.startTime,data);const destination=`show/${show.id}/${Math.floor(pick.startTime)}`;if(!state.randomMode){history.replaceState(null,'','#home');location.hash=destination;state.randomMode=true}else{history.replaceState(null,'',`#${destination}`);render();}}
async function loadIndexes(){await Promise.all(['2006','2007'].map(async year=>{if(!indexes[year])indexes[year]=await fetch(`data/search-${year}.json`).then(response=>response.json())}));}
async function search(query){state.search=query.trim();if(state.search.length<3){if(route()[0]==='search')go('home');return}$('#app').innerHTML='<div class="searching">Searching the transcript library…</div>';await loadIndexes();const words=[...new Set((state.search.toLowerCase().match(/[a-z0-9][a-z0-9']{2,}/g)||[]))],hits=[],seen=new Set();for(const index of Object.values(indexes))for(const word of words)for(const[id,start]of(index[word]||[])){const key=`${id}-${start}`;if(!seen.has(key)){seen.add(key);hits.push({id,start})}}const byId=new Map(allShows().map(show=>[show.id,show])),visible=hits.slice(0,48);const loaded=await Promise.all([...new Set(visible.map(hit=>hit.id))].map(async id=>[id,await loadShowData(id,byId.get(id))]));const dataById=new Map(loaded);const sentence=hit=>{const transcript=dataById.get(hit.id)?.transcript||[];return transcript.find((segment,index)=>hit.start>=segment.startTime&&hit.start<(transcript[index+1]?.startTime??Infinity))||transcript.find(segment=>segment.startTime>=hit.start)||null};$('#app').innerHTML=`<section class="search-results"><p class="kicker">ARCHIVE SEARCH</p><h1>“${esc(state.search)}”</h1><p class="note">${hits.length?'Transcript matches — choose a line to tune in.':'No indexed matches yet. Try a name, topic, or phrase of three or more letters.'}</p><div class="results">${visible.map(hit=>{const show=byId.get(hit.id),line=sentence(hit);return show?`<button class="search-result" data-search-show="${hit.id}" data-search-time="${hit.start}"><span>${show.date} · ${time(hit.start)}</span><strong>${esc(title(show))}</strong><p class="search-snippet">${line?highlight(line.text,words):'Transcript moment'}</p><em>Play from here</em></button>`:''}).join('')}</div></section>`;}
function historyPage(){const byId=new Map(allShows().map(show=>[show.id,show])),rows=savedHistory().map(item=>({...item,show:byId.get(item.id)})).filter(item=>item.show);$('#app').innerHTML=`<section class="search-results history-page"><p class="kicker">ON THIS DEVICE</p><h1>Listening history</h1><p class="note">Your most recent places on the dial.</p><div class="results">${rows.length?rows.map(item=>`<button class="search-result" data-history="${item.id}" data-history-time="${item.position}"><span>${shortDate(item.date)}</span><strong>${esc(item.title)}</strong><em>${time(item.position)} · ${new Date(item.updatedAt).toLocaleString('en',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</em></button>`).join(''):'<p class="empty">Your first listening session will appear here.</p>'}</div></section>`;}
async function render(){const current=route();if(current[0]==='show'){const id=current[1],at=Number(current[2]||0);await detail(id);if(at&&state.playingShow?.id!==id)play(state.show,at,state.data)}else if(current[0]==='search')await search(decodeURIComponent(current.slice(1).join('/')));else if(current[0]==='history')historyPage();else{state.randomMode=false;library();}}
document.addEventListener('click',event=>{const show=event.target.closest('[data-show]'),playButton=event.target.closest('[data-play]'),tab=event.target.closest('[data-tab]'),result=event.target.closest('[data-search-show]'),historyButton=event.target.closest('[data-history]');if(show)showRoute(show.dataset.show);else if(result)showRoute(result.dataset.searchShow,result.dataset.searchTime);else if(historyButton)showRoute(historyButton.dataset.history,historyButton.dataset.historyTime);else if(playButton&&state.show){if(playButton.classList.contains('hero-play')){state.playingShow?.id===state.show.id?togglePlayback():play(state.show,0,state.data)}else play(state.show,+playButton.dataset.play,state.data)}else if(tab){state.tab=tab.dataset.tab;renderDetail();syncTranscript()}else if(event.target.closest('#show-back'))history.back();});
function nextSegment(direction){const topics=state.playingData?.topics||[],now=$('#audio').currentTime||0;let index=topics.findIndex((topic,i)=>now>=topic.startTime&&now<(topics[i+1]?.startTime??Infinity));if(index<0)index=direction>0?-1:0;seek(topics[Math.max(0,Math.min(topics.length-1,index+direction))]?.startTime??now);}
$('#back-button').onclick=()=>history.back();$('#random-button').onclick=random;$('#history-button').onclick=()=>go('history');$('#toggle-button').onclick=togglePlayback;$('#player-toggle').onclick=togglePlayback;$('#expanded-toggle').onclick=togglePlayback;$('#player-title').onclick=()=>state.playingShow&&showRoute(state.playingShow.id,$('#audio').currentTime);$('#skip-back').onclick=()=>seek(Math.max(0,$('#audio').currentTime-15));$('#skip-forward').onclick=()=>seek($('#audio').currentTime+15);$('#expanded-back').onclick=()=>seek(Math.max(0,$('#audio').currentTime-15));$('#expanded-forward').onclick=()=>seek($('#audio').currentTime+15);$('#close-player').onclick=closeExpanded;$('#progress').oninput=event=>seek(event.target.value);$('#expanded-progress').oninput=event=>seek(event.target.value);$('#mute-volume').onclick=()=>{const audio=$('#audio');audio.muted=!audio.muted;updatePlayer()};
document.addEventListener('change',event=>{if(event.target.id==='month-wheel'){state.month=+event.target.value;library()}if(event.target.id==='year-wheel'){state.year=event.target.value;library()}});
let searchTimer;$('#global-search').oninput=event=>{clearTimeout(searchTimer);const query=event.target.value;searchTimer=setTimeout(()=>{if(query.trim().length>=3)go(`search/${encodeURIComponent(query.trim())}`);else if(route()[0]==='search')go('home')},220)};
$('#audio').ontimeupdate=()=>{updatePlayer();syncTranscript();if(Date.now()-lastHistoryWrite>5000){remember();lastHistoryWrite=Date.now()}};$('#audio').onloadedmetadata=updatePlayer;$('#audio').onplay=updatePlayer;$('#audio').onpause=()=>{remember();updatePlayer()};$('#audio').onended=remember;
if('mediaSession'in navigator){navigator.mediaSession.setActionHandler('play',()=>$('#audio').play());navigator.mediaSession.setActionHandler('pause',()=>$('#audio').pause());navigator.mediaSession.setActionHandler('seekbackward',()=>seek(Math.max(0,$('#audio').currentTime-15)));navigator.mediaSession.setActionHandler('seekforward',()=>seek($('#audio').currentTime+15));}
let swipeStart=null;$('#app').addEventListener('touchstart',event=>{if(route()[0]==='show'&&event.touches.length===1)swipeStart={x:event.touches[0].clientX,y:event.touches[0].clientY}},{passive:true});$('#app').addEventListener('touchend',event=>{if(!swipeStart||route()[0]!=='show')return;const point=event.changedTouches[0],dx=point.clientX-swipeStart.x,dy=point.clientY-swipeStart.y;swipeStart=null;if(Math.abs(dx)<70||Math.abs(dx)<Math.abs(dy)*1.25)return;const next=dx<0?'transcript':'segments';if(next!==state.tab){state.tab=next;renderDetail();syncTranscript()}},{passive:true});
let playerTouch=null;$('#bottom-player').addEventListener('touchstart',event=>{playerTouch={x:event.touches[0].clientX,y:event.touches[0].clientY}},{passive:true});$('#bottom-player').addEventListener('touchend',event=>{if(playerTouch.y-event.changedTouches[0].clientY>45)openExpanded();playerTouch=null},{passive:true});$('#expanded-player').addEventListener('touchstart',event=>{playerTouch={x:event.touches[0].clientX,y:event.touches[0].clientY}},{passive:true});$('#expanded-player').addEventListener('touchend',event=>{const point=event.changedTouches[0],dx=point.clientX-playerTouch.x,dy=point.clientY-playerTouch.y;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy))nextSegment(dx<0?1:-1);else if(dy>60)closeExpanded();playerTouch=null},{passive:true});
window.onhashchange=render;fetch('data/catalog.json').then(response=>response.json()).then(data=>{state.catalog=data;render()});
